/** uda_ICI.cpp - unidades de aprendizaje */
#include <UnidadDAp.h>
std::string carrera="I.C.I.";
UnidadDAp uda[] = {
 UnidadDAp(0,"Desarrollo de Software Orientado a Objetos"),
 UnidadDAp(1,"Arquitectura de Computadoras I"),
 UnidadDAp(2,"Arquitectura de Computadoras II"),
 UnidadDAp(3,"Inteligencia Artificial"),
 UnidadDAp(4,"Lenguajes de Programacion"),
 UnidadDAp(5,"Ingenieria de Sistemas de Informacion I"),
 UnidadDAp(6,"Sistemas Distribuidos"),
 UnidadDAp(7,"Base de Datos Avanzadas"),
 //UnidadDAp(8,"Base de Datos Avanzadas"),
 UnidadDAp(8,"Organizacion de Computadoras"),
 UnidadDAp(9,"Tecnicas de Produccion de Sistemas"),
 UnidadDAp(10,"Tecnologias de Informacion Emergente"),
 UnidadDAp(11,"Disenio de Compiladores"),
 UnidadDAp(12,"Ingenieria Economica"),
 UnidadDAp(13,"Matematicas Computacionales"),
 UnidadDAp(14,"Programacion Avanzada"),
 UnidadDAp(15,"Lenguaje Ensamblador"),
 UnidadDAp(16,"Probabilidad y Estadistica"),
 UnidadDAp(17,"Ingenieria de Redes I"),
 UnidadDAp(18,"Ingenieria de Redes II"),
 UnidadDAp(19,"Ingenieria de Redes III"),
 UnidadDAp(20,"Programacion"),
 UnidadDAp(21,"Ecuaciones Diferenciales"),
 UnidadDAp(22,"Teoria de la Computacion"),
 UnidadDAp(23,"Topicos Avanzados"),
 UnidadDAp(24,"Sistemas Expertos"),
 UnidadDAp(25,"Programacion Orientada a Objetos"),
 UnidadDAp(26,"Laboratorio de Ingenieria de Redes"),
 UnidadDAp(27,"Simulacion de Sistemas"),
 UnidadDAp(28,"Auditoria y Consultoria Informatica"),
 UnidadDAp(29,"Analisis de Algoritmos"),
 //UnidadDAp(30,"Teoria de la Computacion"),<-----------
 UnidadDAp(30,"Redes Neuronales"),
 UnidadDAp(31,"Estructura de Datos"),
 UnidadDAp(32,"Bases de Datos"),
 UnidadDAp(33,"Ingenieria de Sistemas de Informacion II"),
 UnidadDAp(34,"Algebra Superior"),
 UnidadDAp(35,"Algebra Lineal"),
 UnidadDAp(36,"Arquitecturas de Desarrollo de Software"),
 UnidadDAp(37,"Costos Aplicados a la Ingenieria"),
 UnidadDAp(38,
"Introduccion a la Administracion y Gestion de Proyectos"),
 UnidadDAp(39,"Seguridad Computacional"),
 UnidadDAp(40,"Microprocesadores y Microcontroladores"),
 UnidadDAp(41,"Matematicas Basicas para Ingenieria"),
 UnidadDAp(42,"Calculo Diferencial e Integral"),
 UnidadDAp(43,"Geometria Analitica"),
 UnidadDAp(44,"Matematicas Avanzadas"),
 UnidadDAp(45,"Investigacion de Operaciones I"),
 UnidadDAp(46,"Investigacion de Operaciones II"),
 UnidadDAp(47,"Sistemas Operativos"),
 UnidadDAp(48,"Seniales y Sistemas"),
 UnidadDAp(49,
       "Sistemas Computacionales en ambiente Multimedia"),
 UnidadDAp(50,"Sistemas Expertos"),
 UnidadDAp(51,"Legislacion Informatica"),
 UnidadDAp(52,"Costos Aplicados a la Ingenieria"),
 UnidadDAp(53,"Elaboracion de Tesis Profesional"),
 UnidadDAp(54,"Calculo Vectorial I"),
 UnidadDAp(55,"Calculo Vectorial II"),
 UnidadDAp(56,"Dibujo de Ingenieria"),
 UnidadDAp(57,"Mecanica (Estatica)"),
 UnidadDAp(58,"Electricidad y Magnetismo")
};/*end UnidadDAp uda[]*/
uint N = SIZE_ARR(uda);

