/** uda_ICE.cpp - unidades de aprendizaje*/
#include <UnidadDAp.h>
std::string carrera="I.C.E.";
UnidadDAp uda[] = {
 UnidadDAp(0,"Sistemas de Comunicaciones"),
 UnidadDAp(1,"Seniales y Sistemas I"),
 UnidadDAp(2,"Laboratorio de Ingenieria de Control"),
 UnidadDAp(3,"Comunicaciones por Microondas"),
 UnidadDAp(4,"Sistemas Digitales I"),
 UnidadDAp(5,"Conversion de la Energia II"),
 UnidadDAp(6,"Telefonia"),
 UnidadDAp(7,"Organizacion de Computadoras"),
 UnidadDAp(8,"Campos y Ondas Electromagneticas"),
 UnidadDAp(9,"Electronica II"),
 UnidadDAp(10,"Redes de Telecomunicaciones"),
 UnidadDAp(11,"Conversion de la Energia I"),
 UnidadDAp(12,"Laboratorio de Instrumentacion Virtual"),
 UnidadDAp(13,"Sistemas de Radiocomunicaciones I"),
 UnidadDAp(14,"Laboratorio de Circuitos y Mediciones"),
 UnidadDAp(15,"Laboratorio de Disenio Electronico"),
 UnidadDAp(16,"Amplificacion de Seniales"),
 UnidadDAp(17,"Ingenieria Acustica"),
 UnidadDAp(18,"Microprocesadores y Perifericos"),//<--formatos
 UnidadDAp(19,"Probabilidad y Estadistica"),
 UnidadDAp(20,"Seniales y Sistemas II"),
 UnidadDAp(21,"Sistemas de Video"),
 UnidadDAp(22,"Control Analogico"),
 UnidadDAp(23,"Control Digital"),
 UnidadDAp(24,"Radiacion, Propagacion de Ondas y Antenas"),
 UnidadDAp(25,"Comunicaciones Via Satelite"),
 UnidadDAp(26,"Electronica Analogica y Digital"),
 UnidadDAp(27,"Sistemas Digitales II"),
 UnidadDAp(28,"Sistemas Digitales I"),
 UnidadDAp(29,"Teoria de las Comunicaciones"),
 UnidadDAp(30,"Lineas de Transmision"),
 UnidadDAp(31,"Laboratorio de Sistemas de Comunicacion"),
 UnidadDAp(32,"Arquitectura de Computadoras I"),
 UnidadDAp(33,"Arquitectura de Computadoras II"),
 UnidadDAp(34,"Calculo I"),
 UnidadDAp(35,"Calculo Vectorial"),
 UnidadDAp(36,"Analisis de Circuitos Electricos I"),
 UnidadDAp(37,"Analisis de Circuitos Electricos II"),
 UnidadDAp(38,"Electronica I"),
 UnidadDAp(39,"Analisis de Seniales"),
 UnidadDAp(40,"Ingenieria en Redes I"),
 UnidadDAp(41,"Ingenieria en Redes II"),
 UnidadDAp(42,"Elaboracion de Tesis"),
 UnidadDAp(43,"Electricidad y Magnetismo"),
 UnidadDAp(44,"Conversion de la Energia II"),
 UnidadDAp(45,"Laboratorio de Sistemas Digitales I"),
 UnidadDAp(46,"Matematicas Avanzadas"),
 UnidadDAp(47,"Circuitos Integrados Analogicos"),
 UnidadDAp(48,"Medicion e Instrumentacion"),
 UnidadDAp(49,"Dispositivos Electronicos"),
 UnidadDAp(50,"Electronica de Potencia"),
 UnidadDAp(51,"Electronica Analogica"),
 UnidadDAp(52,"Ingenieria Acustica II"),
 UnidadDAp(53,"Inteligencia Artificial"),
 UnidadDAp(54,"Sistemas de Radiocomunicaciones II"),
 UnidadDAp(55,"Calculo Diferencial e Integral"),
 UnidadDAp(56,"Redes Neuronales Artificiales"),
 UnidadDAp(57,"Programacion Avanzada"),
 UnidadDAp(58,"Programacion")
};/*end UnidadDAp uda[]*/
uint N = SIZE_ARR(uda);


